name: Update Environment

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'environment.yml'
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        IMAGE_TAG=exampleenv:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "Image Tag: $IMAGE_TAG"

